# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('otherForm', models.CharField(blank=True, default='', max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Level')),
                ('wordType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.WordType')),
            ],
        ),
    ]
