# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0003_passage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=tinymce.models.HTMLField(default='add content'),
        ),
    ]
