# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0006_auto_20160922_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='translation',
            field=models.TextField(default=''),
        ),
    ]
