# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0007_auto_20160922_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
