# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0008_auto_20160922_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', tinymce.models.HTMLField(default='add content')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typeOf',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vocabs',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
