# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0009_auto_20160922_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('value', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('explanation', models.TextField(default='')),
                ('translation', models.TextField(default='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Level')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Passage')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Topic')),
                ('typeOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Type')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Video')),
                ('vocabs', models.ManyToManyField(to='Toeic.Vocab')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toeic.Question'),
        ),
    ]
