# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0010_auto_20160922_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grammarTopics',
            field=models.ManyToManyField(to='Toeic.GrammarTopic'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='Toeic.Topic'),
        ),
    ]
