# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0011_auto_20160922_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
