# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0012_auto_20160922_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='true',
            new_name='isTrue',
        ),
    ]
