# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0013_auto_20160922_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='isTestSix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(to='Toeic.Test'),
        ),
    ]
