# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toeic', '0015_question_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='topic',
            field=models.ManyToManyField(to='Toeic.Topic'),
        ),
    ]
